categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles the python environment for mutationseq version 4.3.6
name: package_mutationseq_python_environment_4_3_6
owner: morinlab
remote_repository_url: https://github.com/morinlab/tools-morinlab/tree/master/packages/package_mutationseq_python_environment_4_3_6
type: tool_dependency_definition
