categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles vcf2maf version 1.6.7 
name: package_vcf2maf_1_6_7
owner: morinlab
remote_repository_url: https://github.com/morinlab/tools-morinlab/tree/master/packages/package_vcf2maf_1_6_7
type: tool_dependency_definition
