categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles oncodrivefm version 0.6.0
name: package_oncodrivefm_0_6_0
owner: morinlab
remote_repository_url: https://github.com/morinlab/tools-morinlab/tree/master/packages/package_oncodrivefm_0_6_0
type: tool_dependency_definition
