categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles seqtk version 1.0.0
name: package_seqtk_1_0_0
owner: morinlab
remote_repository_url: https://github.com/morinlab/tools-morinlab/tree/master/packages/package_seqtk_1_0_0
type: tool_dependency_definition
