categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles mysql version 6.1.0
name: package_mysql_6_1_0
owner: morinlab
remote_repository_url: https://github.com/morinlab/tools-morinlab/tree/master/packages/package_mysql_6_1_0
type: tool_dependency_definition
