categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles requests version 2.0.1
name: package_requests_2_0_1
owner: morinlab
remote_repository_url: https://github.com/morinlab/tools-morinlab/tree/master/packages/package_requests_2_0_1
type: tool_dependency_definition
