categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles libpng version 1.6.7
name: package_libpng_1_6_7
owner: morinlab
remote_repository_url: https://github.com/morinlab/tools-morinlab/tree/master/packages/package_libpng_1_6_7
type: tool_dependency_definition
