categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles hmmcopy version 0.1.1
name: package_hmmcopy_0_1_1
owner: morinlab
remote_repository_url: https://github.com/morinlab/tools-morinlab/tree/master/packages/package_hmmcopy_0_1_1
type: tool_dependency_definition
