categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles FACTERA version 1.4.3 
name: package_factera_1_4_3
owner: morinlab
remote_repository_url: https://github.com/morinlab/tools-morinlab/tree/master/packages/package_factera_1_4_3
type: tool_dependency_definition
