categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles Strelka version 1.0.14
name: package_strelka_1_0_14
owner: morinlab
remote_repository_url: https://github.com/morinlab/tools-morinlab/tree/master/packages/package_strelka_1_0_14
type: tool_dependency_definition
