categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles vardictjava version 1.4.6
name: package_vardictjava_1_4_6
owner: morinlab
remote_repository_url: https://github.com/morinlab/tools-morinlab/tree/master/packages/package_vardictjava_1_4_6
type: tool_dependency_definition
