categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles libgd version 2.1
name: package_libgd_2_1
owner: morinlab
remote_repository_url: https://github.com/morinlab/tools-morinlab/tree/master/packages/package_libgd_2_1
type: tool_dependency_definition
