categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles pindel version 0.2.5b8
name: package_pindel_0_2_5b8
owner: morinlab
remote_repository_url: https://github.com/morinlab/tools-morinlab/tree/master/packages/package_pindel_0_2_5b8
type: tool_dependency_definition
