categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles the perl environment for Ensembl VEP version 84 
name: package_ensembl_vep_perl_environment_84
owner: morinlab
remote_repository_url: https://github.com/morinlab/tools-morinlab/tree/master/packages/package_ensembl_vep_perl_environment_84
type: tool_dependency_definition
