categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles titancna version 1.8.0
name: package_titancna_1_8_0
owner: morinlab
remote_repository_url: https://github.com/morinlab/tools-morinlab/tree/master/packages/package_titancna_1_8_0
type: tool_dependency_definition
