categories:
- Variant Analysis
description: OncodriveFM - an approach to uncover driver genes or gene modules 
name: oncodrivefm
owner: morinlab
remote_repository_url: https://github.com/morinlab/tools-morinlab/tree/master/tools/oncodrivefm
type: unrestricted
