categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles zlib version 1.2.8
name: package_zlib_1_2_8
owner: morinlab
remote_repository_url: https://github.com/morinlab/tools-morinlab/tree/master/packages/package_zlib_1_2_8
type: tool_dependency_definition
