categories:
- Variant Analysis
description: Sequenza - enables the efficient estimation of tumor cellularity and ploidy, and generation of copy number, loss-of-heterozygosity, and mutation frequency pro-files
name: sequenza
owner: morinlab
remote_repository_url: https://github.com/morinlab/tools-morinlab/tree/master/tools/sequenza
type: unrestricted
