categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles radia version 1.1.3
name: package_radia_1_1_3
owner: morinlab
remote_repository_url: https://github.com/morinlab/tools-morinlab/tree/master/packages/package_radia_1_1_3
type: tool_dependency_definition
