categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles BPG version 5.3.4
name: package_boutroslab_plotting_general_5_3_4
owner: morinlab
remote_repository_url: https://github.com/morinlab/tools-morinlab/tree/master/packages/package_boutroslab_plotting_general_5_3_4
type: tool_dependency_definition
